version: '3'

services: 
    logic:
        build: .
        image: aiogram
        container_name: logic
        env_file: .env
        restart: on-failure
        depends_on: 
            - postgres
    
    postgres:
        image: postgres
        container_name: database
        restart: on-failure
        volumes:
            - postgres:/var/lib/postgresql/data
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=changeme
        ports: 
            - 5432:5432

volumes:
    postgres: